# -*- coding: utf-8 -*-
"""hat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yIirY7Rx6C9FRFos0fIdBwiP2S51fJ9b

# Integrar com o Drive
"""

from google.colab import drive
drive.mount('/content/drive')

"""# Resgatar repositorio Git

---





"""

# Commented out IPython magic to ensure Python compatibility.
# Clonar o repositório
!git clone https://github.com/XPixelGroup/HAT.git
# %cd HAT

"""# Instalar dependencias

"""

!pip install basicsr==1.3.4.9
!pip install -r requirements.txt
!python setup.py develop

"""# Copiar e enviar modelo pre treinado para o arquivo local

Baixar modelo pré treinado de sua escolha: [acesse aqui](https://drive.google.com/drive/folders/1HpmReFfoUqUbnAOQ7rvOeNU3uf_m69w0)

Este trecho de código cuida de preparar o ambiente para o uso do modelo pré-treinado Real_HAT_GAN_sharper.pth:

🔧 O que ele faz:

```
!mkdir -p experiments/pretrained_models

Cria a pasta experiments/pretrained_models onde o modelo será armazenado (sem erro se a pasta já existir).

!cp /content/drive/MyDrive/Real_HAT_GAN_sharper.pth experiments pretrained_models/

Copia o arquivo de pesos pré-treinados do Google Drive para a pasta local esperada pelo script de inferência.
```

✅ Isso garante que o modelo estará no caminho correto (experiments/pretrained_models/Real_HAT_GAN_sharper.pth) para ser carregado automaticamente durante a execução do pipeline.
"""

#Baixar modelo pre treinados
!mkdir -p experiments/pretrained_models
!cp /content/drive/MyDrive/Real_HAT_GAN_sharper.pth experiments/pretrained_models/

"""# Criar arquivo de configuração

Este trecho de código cria um arquivo de configuração YAML necessário para executar o teste de Super-Resolução com o modelo Real_HAT_GAN_sharper.pth no framework HAT.

🔧 O que ele faz:
Cria a pasta options/test (caso ainda não exista).

Escreve um arquivo de configuração chamado Real_HAT_GAN_sharper.pth.yml com os parâmetros do modelo e dataset.

Define o caminho das imagens de entrada (dataroot_lq) como /content/drive/MyDrive/inputs_imgs.

Especifica a arquitetura do modelo HAT com seus hiperparâmetros.

Aponta para o arquivo de pesos pré-treinados do modelo (pretrain_network_g).

Ativa a opção para salvar as imagens geradas após o processamento (save_img: true).
"""

!mkdir -p options/test
with open("options/test/Real_HAT_GAN_sharper.pth.yml", "w") as f:
    f.write("""
name: Real_HAT_GAN_sharper.pth
model_type: HATModel
scale: 4
num_gpu: 1

datasets:
  test:
    name: demo
    type: SingleImageDataset
    dataroot_lq: /content/drive/MyDrive/inputs_imgs
    io_backend:
      type: disk

network_g:
  type: HAT
  upscale: 4
  in_chans: 3
  img_size: 64
  window_size: 16
  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

path:
  pretrain_network_g: experiments/pretrained_models/Real_HAT_GAN_sharper.pth
  param_key_g: params_ema
  strict_load_g: true
  resume_state: ~

val:
  save_img: true
  suffix: ~
  flip: false
  x4: true
""")

"""

### 🛠️ **Correção de Import no `basicsr`**

#### 📌 O que o comando faz:

```bash
!sed -i 's/from torchvision.transforms.functional_tensor import rgb_to_grayscale/from torchvision.transforms.functional import rgb_to_grayscale/' /usr/local/lib/python3.11/dist-packages/basicsr/data/degradations.py
```

#### 🔧 Explicação:

Este comando corrige um **erro de importação** no arquivo `degradations.py` da biblioteca `basicsr`.

- Ele substitui:
  ```python
  from torchvision.transforms.functional_tensor import rgb_to_grayscale
  ```
  por:
  ```python
  from torchvision.transforms.functional import rgb_to_grayscale
  ```

#### 🧠 Por quê?

A função `rgb_to_grayscale` foi movida de `functional_tensor` para `functional` nas versões mais recentes do `torchvision`.  
Sem essa correção, o código apresentaria erro ao tentar importar a função.

✅ **Esse patch garante compatibilidade com a versão atual do `torchvision` instalada no Colab.**
"""

!sed -i 's/from torchvision.transforms.functional_tensor import rgb_to_grayscale/from torchvision.transforms.functional import rgb_to_grayscale/' /usr/local/lib/python3.11/dist-packages/basicsr/data/degradations.py

"""

### 🧪 **Execução de Teste com HAT + Limpeza de Resultados Anteriores**

```python
# Apaga qualquer teste anterior
!rm -rf /content/HAT/results/Real_HAT_GAN_sharper*

# Roda o seu test.py normalmente com a configuração definida no YAML
!python hat/test.py -opt options/test/Real_HAT_GAN_sharper.pth.yml
```

#### ✅ O que faz:

- **Limpa os resultados anteriores**: remove o diretório `/content/HAT/results/Real_HAT_GAN_sharper*`, garantindo que apenas os novos resultados da execução atual sejam considerados.
- **Executa o teste com o modelo HAT**: utiliza o arquivo YAML `Real_HAT_GAN_sharper.pth.yml` com as configurações do modelo e caminho para as imagens de entrada.
- As imagens de saída (super-resolvidas) são salvas automaticamente no diretório:
  ```
  /content/HAT/results/Real_HAT_GAN_sharper/visual
  ```
"""

# apaga qualquer teste anterior
!rm -rf /content/HAT/results/Real_HAT_GAN_sharper*

# roda o seu test.py normalmente
!python hat/test.py -opt options/test/Real_HAT_GAN_sharper.pth.yml

!ls -lh /content/HAT/experiments/pretrained_models/